name: Update GitHub Skyline

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs monthly on the first day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh figlet -y

      - name: Install gh-skyline extension
        run: gh extension install github/gh-skyline

      - name: Generate ASCII Art Header
        run: |
          figlet "Thanks for your interest, here you can see my github skyline from last year" > header.txt

      - name: Generate Skyline ASCII Art for Last Year
        run: |
          last_year=$(date -d "last year" +'%Y')
          echo "Generating Skyline for year: $last_year"
          gh skyline --user "${{ github.repository_owner }}" --year "$last_year" --art-only > skyline.txt

      - name: Combine Header and Skyline
        run: |
          echo '```text' > combined.txt
          cat header.txt >> combined.txt
          echo "" >> combined.txt
          cat skyline.txt >> combined.txt
          echo '```' >> combined.txt

      - name: Update README with Combined ASCII Art
        run: |
          awk '/<!-- skyline start -->/{print; system("cat combined.txt"); flag=1; next} /<!-- skyline end -->/{flag=0} !flag {print}' README.md > README.new.md
          mv README.new.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -am "Update GitHub Skyline with custom header" || echo "No changes to commit"
          git push
