name: Update GitHub Skyline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:   # Allows manual trigger

jobs:
  update-skyline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Install gh-skyline extension
        run: |
          gh extension install github/gh-skyline

      - name: Generate Skyline ASCII Art for Last Year
        run: |
          # Calculate the last complete year dynamically
          last_year=$(date -d "last year" +'%Y')
          echo "Generating Skyline for year: $last_year"
          gh skyline --year "$last_year" --art-only > skyline.txt

      - name: Update README with Skyline
        run: |
          # Replace content between the markers in README.md with the new skyline
          awk '/<!-- skyline start -->/{print; system("cat skyline.txt"); flag=1; next} /<!-- skyline end -->/{flag=0} !flag {print}' README.md > README.new.md
          mv README.new.md README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update GitHub Skyline for last year" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
